site_name: AWS Nuke
site_url: https://ekristen.github.io/aws-nuke
site_author: Erik Kristensen
site_description: >-
  AWS Nuke is a tool to clean up your AWS account by nuking (deleting) all resources within it.

repo_name: ekristen/aws-nuke
repo_url: https://github.com/ekristen/aws-nuke

copyright: Copyright &copy; 2024 - Erik Kristensen

site_dir: public

# Configuration
theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - toc.follow
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

# Page tree
nav:
  - Getting Started:
    - Overview: index.md
    - Warning: warning.md
    - Install: installation.md
    - Authentication: auth.md
    - Quick Start: quick-start.md
    - Starter Config: starter-config.md
    - Migration Guide: migration-guide.md
  - Features:
    - Overview: features/overview.md
    - Bypass Alias Check: features/bypass-alias-check.md
    - Global Filters: features/global-filters.md
    - Filter Groups: features/filter-groups.md
    - Enabled Regions: features/enabled-regions.md
    - Signed Binaries: features/signed-binaries.md
  - CLI:
    - Usage: cli-usage.md
    - Options: cli-options.md
    - Shell Completion: cli-completion.md
    - Experimental: cli-experimental.md
    - Examples: cli-examples.md
  - Config:
    - Overview: config.md
    - Filtering: config-filtering.md
    - Presets: config-presets.md
    - Custom Endpoints: config-custom-endpoints.md
    - Migration Guide: config-migration.md
    - Examples & Presets: config-contrib.md
  - Development:
    - Overview: development.md
    - Documentation: documentation.md
    - Contributing: contributing.md
    - Standards: standards.md
    - Resources: resources.md
    - Releases: releases.md
    - Testing: testing.md
  - Resources:
    - Overview: resources/overview.md
    - ACM Certificate: resources/acm-certificate.md
    - ACMPCA Certificate Authority State: resources/acmpca-certificate-authority-state.md
    - ACMPCA Certificate Authority: resources/acmpca-certificate-authority.md
    - Access Analyzer Archive Rule: resources/access-analyzer-archive-rule.md
    - Access Analyzer: resources/access-analyzer.md
    - Cognito User Pool: resources/cognito-user-pool.md
    - EC2 Image: resources/ec2-image.md
    - EC2 Instance: resources/ec2-instance.md
    - ELBv2: resources/elbv2.md
    - El Bv2: resources/el-bv2.md
    - IAM Role: resources/iam-role.md
    - Lightsail Instance: resources/lightsail-instance.md
    - S3 Bucket: resources/s3-bucket.md
    - S3 Object: resources/s3-object.md
